---
title: "Data Manipulation"
author: Lin Yang
date: 2021-09-28
output: github_document
 

---

```{r}
library(tidyverse)

litters_df = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_df = janitor::clean_names(pups_df)
```


## `select`

Let's select some columns.

```{r}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)
select(litters_df, group:gd_of_birth)
select(litters_df, group, starts_with("pups"))
select(litters_df, -litter_number)
select(litters_df, GROUP = group, litter_number)
rename(litters_df, GROUP = group)
select(litters_df, litter_number, everything())
relocate(litters_df, litter_number)

select(litters_df, group)
pull(litters_df, group)
```

```{r}
select(pups_df, litter_number, sex, pd_ears)
```


## `filter`

Let's get rid of rows ...


```{r}
filter(litters_df, gd_of_birth == 20) 
filter(litters_df, group == "Con7")
filter(litters_df, gd0_weight < 23)
filter(litters_df, pups_survive != 4)
filter(litters_df, !(group == "Con7"))
filter(litters_df, group %in% c("Con7", "Con8"))
filter(litters_df, group == "Con7", gd_of_birth == 20)
filter(litters_df, group == "Con7" | gd_of_birth == 20)
drop_na(litters_df, gd0_weight)
```






