---
title: "Tidy Data"
author: Lin Yang
date: 2021-09-28
output: github_document
 

---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## pivot longer
##don't use `gather` always use `pivot_longer` .

Load the pulse data.

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
```

Let's try to pivot

```{r}
pulse_tidy = 
  pulse_df %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi") %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)) 

pulse_tidy

```

## pivot_wider
##don't use `spread` always use `pivot_wider`

make up a results data table.

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a", "b", "a", "b"),
    group_mean = c(4, 8, 3, 6)
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time", 
    values_from = "group_mean"
  ) %>% 
  knitr::kable()

```


## bind_rows

import the lotR movie words stuff

```{r}
fellowship_df = 
  read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers_df = 
  read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king_df = 
  read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```

```{r}
lotr_tidy = 
  bind_rows(fellowship_df, two_towers_df, return_king_df) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "sex", 
    values_to = "words") %>%
  mutate(race = str_to_lower(race)) %>% 
  relocate(movie)

lotr_tidy

```
###rbind is noteably worse, never use `rbind`, always use `bind_rows` .

## joins

Look at FAS data.

```{r}
litter_data = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>% 
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>% ##sep=3, 3 letters in
  relocate(litter_number) %>% 
  mutate(dose = str_to_lower(dose))

pup_data = 
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>% 
  mutate(
    sex = recode(sex, `1` = "male", `2` = "female"), ## recode:turning an existing value to a new value
    sex = factor(sex)) 
```

Let's join these up!

```{r}
fas_data = 
  left_join(pup_data, litter_data, by = "litter_number") %>% 
  relocate(litter_number, dose, day_of_tx)

fas_data
```










